name: fluttex
description: Customizable Flutter plugin that renders TeX equations blazingly fast.
version: 0.0.1
author: Leon Staufer
homepage: https://github.com/LeonStaufer/fluttex
repository: https://github.com/LeonStaufer/fluttex
issue_tracker: https://github.com/LeonStaufer/fluttex/issues

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.staufer.fluttex
        pluginClass: FluttexPlugin
